# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_activated', models.DateTimeField(null=True)),
                ('client_version', models.CharField(help_text=b'Which client version this config can communicate with', max_length=8)),
                ('algo_id', models.IntegerField(help_text=b'Which counting algorithm to tell the client to use')),
                ('n', models.IntegerField(help_text=b'The size of the polyocubes we want to count')),
                ('n0', models.IntegerField(help_text=b'At which size we want to split the counting')),
                ('max_id', models.IntegerField(help_text=b'Total Number of policubes of size n0 without applying filter. Determined from algo id and n0')),
                ('num_of_jobs', models.IntegerField(help_text=b'To how many jobs we want to split the counting')),
                ('secret_hash_length', models.IntegerField(default=32, help_text=b'Max is 64')),
                ('minutes_before_realloc', models.IntegerField(default=10, help_text=b'Minutes to wait before an unreported job can be reallocated')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_hash', models.CharField(max_length=64)),
                ('low_id', models.IntegerField()),
                ('high_id', models.IntegerField()),
                ('date_allocated', models.DateTimeField(null=True)),
                ('date_reported', models.DateTimeField(null=True)),
                ('results', models.CharField(max_length=1024, null=True)),
                ('cpu_time', models.FloatField(default=0)),
                ('ip_allocated', models.CharField(max_length=15, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting_app.Config')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting_app.Job')),
            ],
        ),
    ]
