# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='comment',
            field=models.CharField(default=' ', help_text=b'User comment', max_length=1000),
            preserve_default=False,
        ),
    ]
